import { Dialog } from '@mui/material';
import React, { useState } from 'react';

const TermsAndConditions = (props) => {

    const dialogStyles = {
        width: '90%',
     };


    return (
        <div>
            {props.isOpen && (
                <Dialog
                    open={props.isOpen}
                    maxWidth={false}
                    PaperProps={{ style : dialogStyles}}
                    onClose={props.handleCloseDialog}
                    aria-labelledby="edit-apartment"
                >
                    <div className="dialog">
                        <div className="dialog-content">
                            <h2>Terms and Conditions</h2>
                            <p>
                                <head>
                                    <title>Terms and Conditions</title>
                                </head>

                                <body>
                                    <h1>TERMS AND CONDITIONS WHEN SIGNING UP FOR A WEBSITE</h1>

                                    <h2>ABOUT US</h2>
                                    <p>Welcome to nowacquire.com nowacquire is an online business portal for newbie startups in India. nowacquire renders a of services take fund from investors and provide to startup Company, LLP, Partnership Firm who has not completed 10 year from the date of registration. nowacquire "website" and nowacquire is owned and maintained by Nowacquire LLP. Having register Office at ,_______________________________________</p>

                                    <h2>AGREEMENT</h2>
                                    <p>Please read the terms and conditions set out below carefully before availing services from our website or mobile application or any other mode. By availing service from our website or mobile application or any other mode including by any computer equipment or by phone/mobile or by any electronic device you agree to be bound by these Terms and Conditions</p>

                                    <h2>GENERAL</h2>
                                    <p>In terms of the Information Technology Act, 2000, this document is an electronic record. Being generated by a computer system it does not require any physical or digital signatures.</p>
                                    <p>The domain name www.nowacquire.com (hereinafter referred to as "the Website") is owned by Nowacquire, having its registered office at __________________________________________________</p>

                                    <h2>USER OBLIGATIONS</h2>
                                    <ol>
                                        <li>By visiting our website and accessing the information, resources, services, products, and tools we provide, you understand and agree to accept and adhere to the terms and conditions as stated in this policy, along with the terms and conditions as stated in our Privacy Policy.</li>
                                        <li>By signup or sign in on our website, you are agreeing to additional terms of use with regard to our product i.e. business chat platform. You are advised to read additional terms of use carefully before sign in to application on your mobile devices.</li>
                                        <li>You further agree there is no intention to solicit any engagements from you which are statutorily mandated to be performed by relevant professionals like practicing CA's, CS's, Lawyers etc. and neither will nowacquire.com be implied to be propagating any non-compliance via write-ups, blog posts, articles, notification, comments etc</li>
                                        <li>You agreed upon that we will use our company email id or mobile number or both in various government application in order to receive OTP so that we can serve you and deliver the requisite service promptly. The rationale behind that our team requires unique token/OTP which carry self-life of shorter time in order to access the application and most of the time you are not available to provide OTP/tokens to us on an immediate basis. Your kind cooperation in this regard is highly appreciated.</li>
                                        <li>We reserve the right to change these terms & conditions from time to time without notice. You acknowledge and agree that it is your responsibility to review these terms & conditions periodically to familiarize yourself with any modifications. Your continued use of this site after such modifications will constitute acknowledgment and agreement of the modified terms and conditions.</li>
                                        <li>In order to avail our professional & other services, you may be required to provide certain information about yourself (such as identification proof, address proof, email, phone number, contact details, etc.). You agree that any information you provide will always be accurate, correct, and up to date.</li>
                                        <li>Accessing</li>
                                    </ol>
                                </body>
                            </p>
                        </div>
                        <button className="close-button" onClick={props.handleCloseDialog}>
                            Close
                        </button>
                    </div>
                </Dialog>
            )}
        </div>
    );
};

export default TermsAndConditions;
